Repository jenkinsci/reverse-proxy-auth-plugin, pull requests merged in 2024-11, with the labels that each got.

#141 Add functional test
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .gitignore
  Jenkinsfile
  pom.xml
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealm.java
  src/test/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/reverse_proxy_auth/docker/PlanetExpressTest.java
Labels: test

#148 Update dependencies with Renovate
  .github/dependabot.yml
  .github/renovate.json
  src/test/java/org/jenkinsci/plugins/reverse_proxy_auth/docker/PlanetExpressTest.java
Labels: skip-changelog

#147 [JENKINS-74800] Reverse Proxy Auth plugin 1.7.7 fails with 2.479.1
  pom.xml
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/BindAuthenticator2.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySearchTemplate.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealm.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/auth/DefaultReverseProxyAuthenticator.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/auth/DefaultReverseProxyAuthoritiesPopulator.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/auth/ReverseProxyAuthenticationProvider.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/auth/ReverseProxyAuthoritiesPopulator.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/auth/ReverseProxyAuthoritiesPopulatorImpl.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/data/GroupSearchTemplate.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/data/SearchTemplate.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/data/UserSearchTemplate.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/model/ReverseProxyUserDetails.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/service/ProxyLDAPAuthoritiesPopulator.java
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/service/ProxyLDAPUserDetailsService.java
  src/test/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealmTest.java
  src/test/java/org/jenkinsci/plugins/reverse_proxy_auth/docker/PlanetExpressTest.java
  src/test/resources/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealmTest/config.xml
Labels: bug

#153 [JENKINS-74842] `ClassCastException` in `ReverseProxySecurityRealm#loadGroupByGroupname2`
  src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealm.java
Labels: bug

#154 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: chore
